---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-firefox
description: Install firefox clients through ansible
tags:
  - ansible
  - ansible-role
  - firefox
github:
  has_issues: true
  has_projects: false
  has_wiki: false
